name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew app:bundleProductionRelease
      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/productionRelease
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.0.15
        with: 
          # The service account json private key file to authorize the upload request
          #serviceAccountJson: # optional
          # The raw json text of the service account private key to authorize the upload request
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON_PLAIN_TEXT }}
          # The package name, or Application Id, of the app you are uploading
          packageName: 'dev.ramprasad.bloom'
          # The Android release file to upload (.apk or .aab)
          #releaseFile: ${{steps.sign_app.outputs.signedReleaseFile}}
          # The Android release file(s) to upload (.apk or .aab).Separated by  a ',' for multiple artifacts. Supports glob
          releaseFiles: app/build/outputs/bundle/productionRelease/app-production-release.aab
          # The name of this release. If not set it's generated automatically from the APKs versionName
          #releaseName: # optional
          # The track in which you want to assign the uploaded app.
          track: 'production'
          # In-app update priority of the release. All newly added APKs in the release will be considered at this priority. Can take values in the range [0, 5], with 5 the highest priority. Defaults to 0.
          #inAppUpdatePriority: # optional, default is 0
          # Portion of users who should get the staged version of the app. Accepts values between 0.0 and 1.0 (exclusive-exclusive).
          #userFraction: # optional
          # The directory of localized whats new files
          #whatsNewDirectory: # optional
          # The mapping.txt file used to de-obfuscate your stack traces from crash reports
          #mappingFile: # optional
